theme: jekyll-theme-cayman
# plugins:
#   - jekyll-remote-theme
 #  - jekyll-include-cache
 # remote_theme: benbalter/retlab
# remote_theme: mmistakes/minimal-mistakes
#remote_theme: "mmistakes/minimal-mistakes@4.18.1"
